switch (uname)
    case Darwin
        # Homebrew paths, generated by `brew shellenv`
        set -gx HOMEBREW_PREFIX /opt/homebrew
        set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
        set -gx HOMEBREW_REPOSITORY /opt/homebrew
        ! set -q PATH; and set PATH ''
        set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
        ! set -q MANPATH; and set MANPATH ''
        set -gx MANPATH /opt/homebrew/share/man $MANPATH
        ! set -q INFOPATH; and set INFOPATH ''
        set -gx INFOPATH /opt/homebrew/share/info $INFOPATH

        set -gx KERL_CONFIGURE_OPTIONS "--disable-debug --without-javac"
end


# Add Composer bin folder.
fish_add_path ~/.composer/vendor/bin

fish_add_path ~/.docker/bin

# Private home folder bin.
fish_add_path ~/bin

# Disable ads from npm packages.
set -x DISABLE_OPENCOLLECTIVE 1

# Enable CLI history for iex (Elixir).
set -x ERL_AFLAGS "-kernel shell_history enabled"

# NeoVim as man-pager
set -x MANPAGER "nvim +Man!"

# Let everyone know that this is a colour terminal.
set -x TERM xterm-256color

# Set XDG folders explicitly, since some apps don’t use them as defaults.
set -x XDG_CACHE_HOME $HOME/.cache
set -x XDG_CONFIG_HOME $HOME/.config
set -x XDG_DATA_HOME $HOME/.local/share
