#!/usr/bin/env python3

"""
Link all the files from the current dir to the homedir as dotfiles.

Works only on Unix-like operating systems that support symlinks (obviously)
"""

import argparse
import os
from fnmatch import fnmatch
from shutil import rmtree

# Parse commmandline options
parser = argparse.ArgumentParser()
parser.add_argument("-f", "--force", dest="force", action="store_true",
                    help="forcibly overwrite files in the homedir when creating links")

args = parser.parse_args()

# Skip these files (uses fnmatch matching)
skip_list = ['.*', 'linkdotfiles', 'README.markdown']
cwd = os.path.realpath(os.getcwd())
homedir = os.path.expanduser('~')
files = os.listdir(cwd)

for filename in files:
    if True in [fnmatch(filename, pattern) for pattern in skip_list]:
        print('Skipping {0}'.format(filename))
        continue

    source = os.path.join(cwd, filename)
    destination = os.path.join(homedir, '.' + filename)

    if os.path.lexists(destination):
        if args.force:
            print('Deleting {0}'.format(destination))
            try:
                os.remove(destination)
            except OSError:
                try:
                    rmtree(destination)
                except OSError:
                    print('Failed to delete {0}'.format(destination))
                    continue
        else:
            print('Not overwriting {0} since the file exists already and force (-f) is not in effect'.format(destination))
            continue

    print('Creating a link to {0} at {1}.'.format(source, destination))
    os.symlink(source, destination)

print('Done.')

