# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  timeFormat: _2. Jan 06
  shortTimeFormat: 15:04
  nerdFontsVersion: "3"
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
    - externalDiffCommand: difft --color=always
  autoFetch: false
  # Custom GPG handling since we rely on 1Password’s agent.
  overrideGpg: true
update:
  method: "never"
os:
  editPreset: "nvim"
